### PR TITLE
Add 4th argument to  filter() method

### PR DESCRIPTION
**Pull request by Shelob9**
#12

### CODE REVIEW

**Comment by brianium** [comment]
Thanks for the PR! I think this makes sense - but it raises a question for me. 

This library has definitely helped us test code that relies on WordPress actions and filters, especially in environments where `add_action` and `add_filter` are not defined. The `EventEmitterTrait` provides event functionality even when those are not defined. It's mostly comparable to WordPress' functionality - with the exception of `acceptedArgs` in filters.

We have already swept this issue under the rug as you've seen :) - by just forwarding `acceptedArgs` to the WordPress function and not the built-in event emitter.

So I guess my question is - should this matter? I think your interface change is more correct - but the current implementation via the trait will ignore it in test environments. Do you think that is ok? If so - I'm definitely open to merging this.

**Comment by brianium** [comment]
For reference https://github.com/netrivet/wp-event-emitter/blob/master/src/EventEmitterTrait.php#L65

**Comment by Shelob9** [comment]
For context, I am debating writing a plugins API abstraction, <em>again</em> or finding someone else's to use and I read this library, tried it once and was really happy about it, expect this one thing confused me. I need something that I can use in non WordPress projects, but my only test was in WordPress. 

`current implementation via the trait will ignore it in test environments. Do you think that is ok? If so - I'm definitely open to merging this.`
Not sure I agree with the premise of the question. Shouldn't this question be about the built in emitter and not being feature-equal to WP Plugins API? Separate issue, but...

**Comment by jaredh159** [comment]
This looks good, thanks, merging!

**Comment by brianium** [comment]
@Shelob9 - since this was a change to the interface - I tagged this to 5.0.0. Semantic versioning amirite? Thanks again!

**Pull request merged**
