### PR TITLE
match emit signature to wp do_action

### PR DESCRIPTION
**Pull request by jaredh159**

### CODE REVIEW

**Comment by jaredh159** [comment]
maybe this means 3.0.0 too I guess? ¯_(ツ)_/¯

**Comment by brianium** [comment]
@jaredh159 you feel like adding a travis build to this bad brother? 3.0.0 is fine - justsemverthings.tumblr.com

**Comment by jaredh159** [comment]
sure. #YOLO. one sec... :hourglass:

**Comment by jaredh159** [comment]
@brianium `.travis.yml` added, and I set it to test in `PHP 5.3`. I checked and PHPUnit `4.6` is compatible, so building against 5.3 seems reasonable and will ensure that the widest group of people can use this. Hopefully the tests pass!

**Pull request merged**
